version: '2'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    volumes:
      - ./pg_data_dev:/var/lib/postgresql/data
    ports:
      - 5432:5432
  webapp:
    build: .
    user: nobody
    command: python scielomanager/manage.py runserver 0.0.0.0:8000
    environment:
        - DJANGO_SETTINGS_MODULE=scielomanager.settings
        - SCIELOMANAGER_SETTINGS_FILE=scielomanager/scielomanager/settings_local.include
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/app
    ports:
      - 8777:8000
